models:
  object_one:
    fields:
      name:
        unique: true
      space field:
        required: true
      age:
        type: number
        required: true
      num:
        type: autofield

  object_two:
    fields:
      name:
      object_one:
        type: foreignkey
        to: object_one
